name: Automated Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0    
      - run: |
          gh pr create --fill -B develop 
          gh pr merge --merge
          gh pr create --fill -B develop2
          gh pr merge --merge          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
