name: Automated Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create a pull request
        run: |
          sudo apt-get install hub
          sudo gem install gh 
          #hub pull-request [-focp] [-b main] [-h develop]
