name: Automated Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - run: gh pr create --fill -B develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
